version: 2.0.{build}
image: Visual Studio 2017
configuration: Release
skip_tags: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  
before_build:
- ps: dotnet restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

deploy:
  provider: NuGet
  api_key:
    secure: s+/o11/jSQpFR10rPNSPGa0qztHDUNIVaTt4cgO5JRo1Z35O/kEjsZbjhwlQIBlx
  skip_symbols: false
  on:
    branch: master