version: 2.0.{build}
image: Visual Studio 2017
configuration: Release
skip_tags: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  
before_build:
- ps: dotnet restore

build:
  publish_nuget: true
  publish_nuget_symbols: false
  include_nuget_references: true
  verbosity: minimal

deploy:
  provider: NuGet
  api_key:
    secure: y60D9QQ5jN/RMYEzKugJaKgjFz18PjXi/9Ri1yvlr79TiX5cuLw5nq9M+a+jtmPA
  skip_symbols: false
  on:
    branch: master
